# Relative paths work OK as long as you start the tool from its local dir
template_path: tool

# This folder gets copied into the output directory
template_static_path: assets

# Templates should have filenames starting in template-
default_template: template-doc.html
default_pdf_template: template-forpdf.html

# HTML, PDF, GFM all get output here
out_path: out

# MD files should be here (and in subdirs)
content_path: content

# This folder gets copied into the output directory
content_static_path: img

# PDF creation needs a dir for temporary files
temporary_files_path: /tmp/

default_filters:
    - multicode_tabs
    - standardize_header_ids
    - buttonize
    - callouts
    - badges
    - link_replacement

callout_class: "devportal-callout"

cover_page:
    name: Overview
    html: index.html
    template: template-home.html
    sidebar: disabled

targets:
    # First member is the default that gets built when target not specified
    -   name: local
        display_name: XRP Ledger Dev Portal
        # These github_ fields are used by the template's "Edit on GitHub" link.
        #  Override them with --vars to change which fork/branch to edit.
        github_forkurl: https://github.com/mDuo13/ripple-dev-portal
        github_branch: 5layertest
        recently_updated:
            - tutorial-reliable-transaction-submission.html
            - tutorial-checks-send.html
            - reference-amendments.html

pages:

    -   name: Docs
        md: landing-docs.md
        funnel: Docs
        template: template-landing-docs.html
        html: landing-docs.html
        sidebar: disabled
        targets:
            - local

    -   name: Concepts
        funnel: Docs
        doc_type: Concepts
        html: landing-concepts.html
        template: template-landing-children.html
        blurb: Learn the "what" and "why" behind fundamental aspects of the XRP Ledger.
        targets:
            - local

    -   name: Understanding the XRP Ledger
        funnel: Docs
        doc_type: Concepts
        category: Understanding the XRP Ledger
        html: concept-xrp-ledger.html
        template: template-landing-children.html
        targets:
            - local

    -   md: concept-xrp-ledger-intro.md
        funnel: Docs
        doc_type: Concepts
        category: Understanding the XRP Ledger
        targets:
            - local

    -   name: Payment System
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        html: concept-payment-system.html
        template: template-landing-children.html
        targets:
            - local

    -   md: concept-accounts.md
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        subcategory: Accounts
        targets:
            - local

    -   md: concept-depositauth.md
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        subcategory: Accounts
        targets:
            - local

    -   md: concept-transaction-cost.md
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        targets:
            - local

    -   md: concept-money.md
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        targets:
            - local

    -   md: concept-authorized-trust-lines.md
        funnel: Docs
        doc_type: Concepts
        category: Payment System
        subcategory: Accounts
        targets:
            - local

    -   name: Consensus Network
        funnel: Docs
        doc_type: Concepts
        category: Consensus Network
        html: concept-consensus-network.html
        template: template-landing-children.html
        targets:
            - local

    -   md: concept-amendments.md
        funnel: Docs
        doc_type: Concepts
        category: Consensus Network
        targets:
            - local

    -   md: concept-fee-voting.md
        funnel: Docs
        doc_type: Concepts
        category: Consensus Network
        targets:
            - local

    -   name: Tutorials #TODO: real page content
        funnel: Docs
        doc_type: Tutorials
        template: template-landing-children.html
        blurb: Get step-by-step guidance to perform common tasks with the XRP Ledger.
        targets:
            - local

    -   name:  Send and Receive Money
        funnel: Docs
        doc_type: Tutorials
        category: Send and Receive Money
        template: template-landing-children.html
        targets:
            - local

    -   md: tutorial-reliable-transaction-submission.md
        funnel: Docs
        doc_type: Tutorials
        category: Send and Receive Money
        targets:
            - local

    -   md: tutorial-checks-send.md
        funnel: Docs
        doc_type: Tutorials
        category: Send and Receive Money
        targets:
            - local

    -   name:  Manage the rippled Server
        funnel: Docs
        doc_type: Tutorials
        category: Manage the rippled Server
        template: template-landing-children.html
        targets:
            - local

    -   md: tutorial-rippled-setup.md
        funnel: Docs
        doc_type: Tutorials
        category: Manage the rippled Server
        targets:
            - local

    -   name: References
        funnel: Docs
        doc_type: References
        template: template-landing-references.html
        html: landing-references.html
        sidebar: disabled
        blurb: Look up the ins-and-outs of XRP Ledger APIs, including sample requests and responses.
        targets:
            - local

    -   name: rippled API
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        template: template-landing-children.html
        html: reference-rippled-api.html
        targets:
            - local

    -   name: rippled API Public Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        blurb: Get data from the XRP Ledger and submit transactions using these public API methods.
        html: reference-rippled-public.html
        template: template-landing-children.html
        targets:
            - local

    -   name: Ledger Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Ledger Methods
        template: template-landing-children.html
        html: reference-rippled-public-ledger-methods.html
        targets:
            - local

    -   md: rippled-api-methods/ledger_closed.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Ledger Methods
        targets:
            - local

    -   md: rippled-api-methods/ledger_current.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Ledger Methods
        targets:
            - local

    -   md: rippled-api-methods/ledger_data.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Ledger Methods
        targets:
            - local

    -   name: Account Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Account Methods
        template: template-landing-children.html
        html: reference-rippled-public-account-methods.html
        targets:
            - local

    -   md: rippled-api-methods/account_channels.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Account Methods
        targets:
            - local

    -   md: rippled-api-methods/account_info.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Account Methods
        targets:
            - local

    -   name: Transaction Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Public Methods
        subcategory: Transaction Methods
        template: template-landing-children.html
        html: reference-rippled-public-tx-methods.html
        targets:
            - local

    -   name: rippled API Admin Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Admin Methods
        blurb: Administer a rippled server with these admin API methods.
        html: reference-rippled-admin.html
        template: template-landing-children.html
        targets:
            - local

    -   name: Server Control Methods
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Admin Methods
        subcategory: Server Control Methods
        html: reference-rippled-admin-server-control-methods.html
        template: template-landing-children.html
        targets:
            - local

    -   md: rippled-api-methods/ledger_accept.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: rippled API Admin Methods
        subcategory: Server Control Methods
        targets:
            - local

    -   md: reference-transaction-format.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: Transaction Format
        blurb: A transaction is the only way to modify the XRP Ledger. Get details about its required format.
        targets:
            - local

    -   name: Transaction Common Fields #TODO: replace with real md file
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: Transaction Format
        html: reference-rippled-transactions-common-fields.html
        targets:
            - local

    -   name: Transaction Types #TODO: replace with real md file
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: Transaction Format
        html: reference-rippled-transaction-types.html
        targets:
            - local

    -   name: Transaction Results #TODO: replace with real md file
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: Transaction Format
        html: reference-rippled-transaction-results.html
        targets:
            - local

    -   md: reference-ledger-format.md
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: Ledger Data Format
        blurb: Learn about individual data objects that comprise the XRP Ledger's shared state.
        targets:
            - local

    -   name: API Conventions #TODO: replace with real md file
        funnel: Docs
        doc_type: References
        supercategory: rippled API
        category: API Conventions
        html: reference-rippled-api-conventions.html
        blurb: Lorem ipsum dolor sit amet...
        targets:
            - local

    -   md: reference-data-api.md
        funnel: Docs
        doc_type: References
        category: Data API
        blurb: Access more XRP Ledger data, including transaction history and analytics.
        curated_anchors:
            - name: Methods
              anchor: "#api-method-reference"
            - name: API Conventions
              anchor: "#api-conventions"
        targets:
            - local

    -   name: RippleAPI Reference # name is required for remote-sourced files
        md: https://raw.githubusercontent.com/ripple/ripple-lib/0.21.0/docs/index.md
        html: reference-rippleapi.html
        funnel: Docs
        doc_type: References
        category: RippleAPI for JavaScript
        blurb: Official client library to the XRP Ledger. Available for JavaScript only.
        curated_anchors:
            - name: Transactions
              anchor: "#transaction-overview"
            - name: Basic Types
              anchor: "#basic-types"
            - name: Methods
              anchor: "#api-methods"
        filters:
            - remove_doctoc
            - add_version
        targets:
            - local

    -   md: use-cases.md
        funnel: Use Cases
        filters:
            - buttonize
        targets:
            - local

    -   md: tutorial-listing-xrp.md # TODO: split up and rename?
        funnel: Use Cases
        targets:
            - local

    -   md: use-case-listing-xrp.md
        funnel: Use Cases
        template: template-use-case.html
        useful_background:
            - concept-xrp-ledger-intro.html
            - tutorial-reliable-transaction-submission.html
            - concept-money.html
        targets:
            - local

    -   md: dev-tools.md
        funnel: Dev Tools
        filters:
            - buttonize
        targets:
            - local

    -   name: RPC Tool
        funnel: Dev Tools
        html: xrp-ledger-rpc-tool.html
        targets:
            - local
        template: template-xrp-ledger-rpc-tool.html

    -   name: WebSocket API Tool
        funnel: Dev Tools
        template: template-ripple-api-tool.html
        html: websocket-api-tool.html
        targets:
            - local

    -   name: Data API v2 Tool
        funnel: Dev Tools
        html: data-api-v2-tool.html
        methods_js: js/apitool-methods-data_v2.js
        rest_host: https://data.ripple.com
        doc_page: reference-data-api.html
        sidebar: custom
        targets:
            - local
        template: template-rest-api-tool.html

    -   name: ripple.txt Validator
        funnel: Dev Tools
        html: ripple-txt-validator.html
        targets:
            - local
        template: template-ripple-txt-validator.html

    -   name: XRP Test Net Faucet
        funnel: Dev Tools
        html: xrp-test-net-faucet.html
        targets:
            - local
        template: template-test-net.html

    -   md: news.md
        funnel: News
        targets:
            - local

    -   md: reference-amendments.md # TODO: rename to news-amendments.md
        funnel: News
        targets:
            - local


ignore_anchors_in:
    - data-api-v2-tool.html
    - ripple-api-tool.html
    - tool-jsonrpc.html

#Sometimes, a link is not really problematic, but the link checker detects it
# as such and the easiest solution is to ignore it.
known_broken_links:
    # Strangely, Python doesn't like the cert here. Firefox is OK with it.
    - https://validators.ripple.com

    # Login required for the client portal.
    - https://clients.ripple.com/

    # These PDFs download OK in a browser
    - http://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A32015R0847
    - http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=OJ:L:2006:345:0001:0009:EN:PDF

# Style Checker Config ------------------------------------------------------ #

word_substitutions_file: tool/word_substitutions.yaml
phrase_substitutions_file: tool/phrase_substitutions.yaml
